# append.TBDB.Drug.Resistance.Details.R -- add TBDB Mutation details to a VCF SNP calls file
#					as generated by the DuffyNGS variant calls pipeline tools

`append.TBDB.Drug.Resistance.Details` <- function( snpFile, tbdbFile="./Cleaned.TBDB.Mutations.csv") {

	# step 1: make sure the mutations file of drug resistance details is readable, and 
	# contains the fields we expect. Allow a data frame or a filename.
	if ( is.data.frame( tbdbFile)) {
		tbdb <- tbdbFile
	} else if (is.null(tbdbFile)) {
		# allow using the data object in DuffyNGS package
		data( "Cleaned.TBDB.Mutations")
		if ( ! exists( "tbdb")) stop( "Failed to load default TBDB Mutations data object from DuffyNGS package")
	} else {
		# allow environment variables in the file path
		tbdbFile <- env.sub( tbdbFile)
		if ( ! file.exists( tbdbFile)) {
			cat( "\n  Info: set argument 'tbdbFile' to NULL to use built-in default mutations data.\n")
			stop( paste( "TBDB Mutations file not found. Tried: ", tbdbFile))
		}
		tbdb <- read.csv( tbdbFile, as.is=T)
	}
	
	# make sure the columns we need are present
	neededColumns <- c( "GENE_ID", "ALT_AA", "ALT_BASE", "POSITION", "Gene", "drug", "type", "source", "confidence")
	if ( ! all( neededColumns %in% colnames(tbdb))) {
		cat( "Error: some needed column names not seen in TBDB mutations file:")
		cat( "\n", setdiff( neededColumns, colnames(tbdb)))
		stop( "Fix mutations file column naming")
	}
	cat( "\nLoaded in TBDB Mutations file.  N_Rows=", nrow(tbdb))
	
	# step 2: make sure the table of SNP calls has all the columns we need
	if ( is.data.frame( snpFile)) {
		snps <- snpFile
		inputWasFile <- FALSE
	} else {
		if ( ! file.exists( snpFile)) stop( paste( "SNP file not found. Tried: ", snpFile))
		snps <- read.delim( snpFile, as.is=T)
		inputWasFile <- TRUE
	}
	neededColumns <- c( "GENE_ID", "ALT_AA", "POSITION", "ALT_BASE")
	if ( ! all( neededColumns %in% colnames(snps))) {
		cat( "Error: some needed column names not seen in SNP variant calls file:")
		cat( "\n", setdiff( neededColumns, colnames(snps)))
		stop( "Perhaps wrong type of SNP results file was given?..")
	}
	cat( "\nLoaded in given SNP VCF results file.  N_Rows=", nrow(snps))

	# step 3:  look up our SNPs
	out <- snps
	out$DrugResistanceDetails <- rep.int( "", nrow(snps))
	
	# create lookup keys in both worlds, to allow fast find of drug resistant SNPs
	# Protein mutations have one style of description, Promoter mutations have a different style
	# note that one SNP may match 2+ drugs, so prepare to allow multiple hits
	
	# do Protein hits first
	tbdbKey1 <- paste( tbdb$GENE_ID, tbdb$ALT_AA, sep="::")
	snpKey1 <- paste( snps$GENE_ID, snps$ALT_AA, sep="::")
	wh <- match( snpKey1, tbdbKey1, nomatch=0)
	hasDrugHit <- which( wh > 0)
	# only allow visiting protein SNPs with actual protein alternate text
	hasDrugHit <- intersect( hasDrugHit, which( snps$ALT_AA != ""))
	
	for ( k in hasDrugHit) {
		# find all the drug rows for this SNP
		hits <- which( tbdbKey1 == snpKey1[k])
		drugStr <- unique( tbdb$drug[hits])
		if ( length(drugStr) > 1) drugStr <- paste( drugStr, collapse="+")
		typeStr <- unique( tbdb$type[hits])
		if ( length(typeStr) > 1) typeStr <- paste( typeStr, collapse=",")
		srcStr <- unique( tbdb$source[hits])
		if ( length(srcStr) > 1) srcStr <- paste( srcStr, collapse=",")
		confStr <- unique( tbdb$confidence[hits])
		if ( length(confStr) > 1) confStr <- paste( confStr, collapse=",")
		# also get the gene name as called by TBDB
		geneStr <- tbdb$Gene[hits[1]]
		drugCall <- paste( "Protein:", geneStr, "; Drug=", drugStr, "; Type=", typeStr, "; Source=", srcStr, "; Confidence=", confStr, sep="")
		out$DrugResistanceDetails[k] <- drugCall
	}
	cat( "\nFound ", length(hasDrugHit), "SNP rows with TBDB protein mutation information")
	
	# promoters are genome positions.  The TBDB mutation is already in A>C notation.
	tbdb2 <- subset( tbdb, ALT_BASE != "")  
	tbdbKey2 <- paste( tbdb2$POSITION, tbdb2$ALT_BASE, sep="::")
	snpKey2 <- paste( snps$POSITION, paste( snps$REF_BASE, snps$ALT_BASE, sep=">"), sep="::")
	
	# do Promoter hits second
	wh <- match( snpKey2, tbdbKey2, nomatch=0)
	hasDrugHit <- which( wh > 0)
	for ( k in hasDrugHit) {
		# find all the drug rows for this SNP
		hits <- which( tbdbKey2 == snpKey2[k])
		drugStr <- unique( tbdb2$drug[hits])
		if ( length(drugStr) > 1) drugStr <- paste( drugStr, collapse="+")
		typeStr <- unique( tbdb2$type[hits])
		if ( length(typeStr) > 1) typeStr <- paste( typeStr, collapse=",")
		srcStr <- unique( tbdb2$source[hits])
		if ( length(srcStr) > 1) srcStr <- paste( srcStr, collapse=",")
		confStr <- unique( tbdb2$confidence[hits])
		if ( length(confStr) > 1) confStr <- paste( confStr, collapse=",")
		# also get the gene name as called by TBDB
		geneStr <- tbdb2$Gene[hits[1]]
		drugCall <- paste( "Promoter:", geneStr, "; Drug=", drugStr, "; Type=", typeStr, "; Source=", srcStr, "; Confidence=", confStr, sep="")
		out$DrugResistanceDetails[k] <- drugCall
	}
	cat( "\nFound ", length(hasDrugHit), "SNP rows with TBDB promoter mutation information")
	
	# done.  Either overwrite the file, or return the data.frame
	if ( inputWasFile) {
		cat( "\nWriting out updated SNP file: ", snpFile)
		write.table( out, snpFile, sep="\t", quote=F, row.names=F)
		return( snpFile)
	} else {
		return( out)
	}
}


